apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    fdk.service: dataset-catalog-etl
  name: dataset-catalog-etl
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      fdk.service: dataset-catalog-etl
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        fdk.service: dataset-catalog-etl
    spec:
      containers:
        - env:
          - name: NAMESPACE
            valueFrom:
              secretKeyRef:
                name: common-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
                key: NAMESPACE
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
                key: MONGO_USERNAME
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
                key: MONGO_PASSWORD
          image: {{ required "Missing value DOCKER_IMAGE_NAME" .Values.DOCKER_IMAGE_NAME }}
          imagePullPolicy: Always
          name: dataset-catalog-etl
          resources:
            requests:
              memory: {{ required "Missing value DATASET_CATALOG_ETL_MEMORY" .Values.DATASET_CATALOG_ETL_MEMORY | quote }}
      restartPolicy: Always
status: {}
